### ISSUE TITLE
tool ruff can't validate lint subsection

### ISSUE THREAD

**Issue by henryiii** [abravalheri/validate-pyproject#185]
The following, from https://github.com/pypa/setuptools_scm/blob/main/pyproject.toml:

```toml
[tool.ruff]
fix = true
lint.select = ["E", "F", "B", "U", "YTT", "C", "DTZ", "PYI", "PT", "I", "FURB", "RUF"]
lint.ignore = ["B028"]
lint.preview = true

[tool.ruff.lint.isort]
force-single-line = true
from-first = false
lines-between-types = 1
order-by-type = true
```

Using https://json.schemastore.org/ruff.json (from validate-pyproject-scheme-store) produces:

```
Invalid file: pyproject.toml
[ERROR] `tool.ruff.lint` cannot be validated by any definition:

    - type: table
      keys:
        ...
        'isort':
          at least one of the following:
            - {}
            - {type: null}
        ...
```

Maybe multiple refs are not supported? See https://github.com/scientific-python/repo-review/issues/232.
