### ISSUE TITLE
Configuration idea

### ISSUE THREAD

**Issue by henryiii** [abravalheri/validate-pyproject#236]
I was thinking, what if we added some options into `tool.validate-pyproject`? Here's an example of all the options I could come up with, though initially I was thinking about #221:

```toml
[tool.validate-pyproject]
check.classifiers = true  #221
check.files = false       #89
enable = []               # List of plugins to enable, empty for all available
disable = []              # List of plugins to ignore
```

This would allow us to add default-off checks (example `files`, above) and default-on (or auto) checks (`classifiers`) above. We could also make these CLI options and/or environment variables.  I've done similar things for scikit-build-core (toml, env, and config-settings), cibuildwheel (toml and env), and repo-review (toml only). Thoughts?
